// Code generated by hertz generator.

package main

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/hertz-contrib/cors"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/xh-polaris/gopkg/hertz/middleware"
	xhlog "github.com/xh-polaris/gopkg/util/log"
	"github.com/xh-polaris/innospark-core-api/biz/adaptor"
	application "github.com/xh-polaris/innospark-core-api/biz/application/service/base"
	"github.com/xh-polaris/innospark-core-api/biz/infra/config"
	"github.com/xh-polaris/innospark-core-api/pkg/logs"
	"github.com/xh-polaris/innospark-core-api/provider"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/contrib/propagators/b3"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"
)

func Init() {
	// 初始化依赖注入
	provider.Init()
	// 初始化自定义日志
	hlog.SetLogger(xhlog.NewHlogLogger())

	// 根据环境设置不同的日志级别
	c := config.GetConfig()
	if c.State == "debug" {
		logs.SetLevel(logs.LevelDebug)
	} else if c.State == "test" {
		logs.SetLevel(logs.LevelInfo)
	} else {
		logs.SetLevel(logs.LevelWarn)
	}

	// 设置openTelemetry的传播器，用于分布式追踪中传递上下文信息
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(b3.New(), propagation.Baggage{}, propagation.TraceContext{}))
	http.DefaultTransport = otelhttp.NewTransport(http.DefaultTransport)
	// 初始化application依赖的基础组件
	application.InitApp()
}

func main() {
	Init()
	c := provider.Get().Config

	// 创建服务器追踪器
	tracer, cfg := tracing.NewServerTracer()
	// 创造hertz服务器实例
	h := server.New(
		server.WithHostPorts(c.ListenOn),
		server.WithTracer(prometheus.NewServerTracer(":9091", "/server/metrics")),
		tracer,
	)

	h.NoHijackConnPool = true

	corsConf := cors.DefaultConfig()
	corsConf.AllowAllOrigins = true
	corsConf.AllowHeaders = []string{"*"}
	corsHandler := cors.New(corsConf)

	h.Use(corsHandler)
	// 增加全局中间件链
	h.Use(tracing.ServerMiddleware(cfg), middleware.EnvironmentMiddleware, recovery.Recovery(), func(ctx context.Context, c *app.RequestContext) {
		ctx = adaptor.InjectContext(ctx, c)
		c.Next(ctx)
	})

	// 注册路由
	register(h)
	logs.Info("server start")

	h.Spin()
}
