// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/innospark-core-api/biz/adaptor"
	core_api "github.com/xh-polaris/innospark-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/innospark-core-api/provider"
)

// Completions .
// @router /v1/completions [POST]
func Completions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CompletionsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	_, err = provider.Get().CompletionsService.Completions(c, ctx, &req)
	adaptor.PostProcess(ctx, c, &req, nil, err)
}

// CreateConversation .
// @router /conversation/create [POST]
func CreateConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.CreateConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// Generate .
// @router /conversation/brief [POST]
func Generate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GenerateBriefReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.GenerateBrief(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// RenameConversation .
// @router /conversation/rename [POST]
func RenameConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.RenameConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.RenameConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListConversation .
// @router /conversation/list [POST]
func ListConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.ListConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetConversation .
// @router /conversation/get [POST]
func GetConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.GetConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// DeleteConversation .
// @router /conversation/delete [POST]
func DeleteConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.DeleteConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SearchConversation .
// @router /conversation/search [POST]
func SearchConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SearchConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().ConversationService.SearchConversation(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListAgents .
// @router /agents/list [POST]
func ListAgents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListAgentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListAgentsResp)

	c.JSON(consts.StatusOK, resp)
}

// Feedback .
// @router /feedback [POST]
func Feedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.FeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().FeedbackService.Feedback(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SendVerifyCode .
// @router /system/send_verify_code [POST]
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SendVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.SendVerifyCode(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// BasicUserRegister .
// @router /basic_user/register [POST]
func BasicUserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.BasicUserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.Register(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// BasicUserLogin .
// @router /basic_user/login [POST]
func BasicUserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.BasicUserLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.Login(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// BasicUserResetPassword .
// @router /basic_user/reset_password [POST]
func BasicUserResetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.BasicUserResetPasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.ResetPassword(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// BasicUserUpdateProfile
// @router /basic_user/update_profile [PATCH]
func BasicUserUpdateProfile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.BasicUserUpdateProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.UpdateProfile(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ThirdPartyLogin .
// @router /thirdparty/login [POST]
func ThirdPartyLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ThirdPartyLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().UserService.ThirdPartyLogin(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
