// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	basic "github.com/xh-polaris/innospark-core-api/biz/application/dto/basic"
	core_api "github.com/xh-polaris/innospark-core-api/biz/application/dto/core_api"
)

// Completion .
// @router /v1/completion [POST]
func Completion(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CompletionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.SSEEvent)

	c.JSON(consts.StatusOK, resp)
}

// ListHistory .
// @router /history/list [POST]
func ListHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListHistoryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListHistoryResp)

	c.JSON(consts.StatusOK, resp)
}

// GetHistory .
// @router /history/get [POST]
func GetHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetHistoryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetHistoryResp)

	c.JSON(consts.StatusOK, resp)
}

// ListAgents .
// @router /agents/list [POST]
func ListAgents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListAgentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListAgentsResp)

	c.JSON(consts.StatusOK, resp)
}

// Feedback .
// @router /feedback [POST]
func Feedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.FeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basic.Response)

	c.JSON(consts.StatusOK, resp)
}
