// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/innospark-core-api/biz/adaptor"
	basic "github.com/xh-polaris/innospark-core-api/biz/application/dto/basic"
	core_api "github.com/xh-polaris/innospark-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/innospark-core-api/provider"
)

// Completions .
// @router /v1/completions [POST]
func Completions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CompletionsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().CompletionsService.Completions(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListConversation .
// @router /conversation/list [POST]
func ListConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListConversationResp)

	c.JSON(consts.StatusOK, resp)
}

// GetConversation .
// @router /conversation/get [POST]
func GetConversation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetConversationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetConversationResp)

	c.JSON(consts.StatusOK, resp)
}

// ListAgents .
// @router /agents/list [POST]
func ListAgents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListAgentsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.ListAgentsResp)

	c.JSON(consts.StatusOK, resp)
}

// Feedback .
// @router /feedback [POST]
func Feedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.FeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basic.Response)

	c.JSON(consts.StatusOK, resp)
}
