// Code generated by hertz generator.

package core_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/xh-polaris/innospark-core-api/biz/adaptor"
	"github.com/xh-polaris/innospark-core-api/biz/application/dto/core_api"
	"github.com/xh-polaris/innospark-core-api/provider"
)

// ListIntelligence .
// @router /intelligence/list [POST]
func ListIntelligence(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListIntelligenceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().IntelligenceService.ListIntelligence(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetIntelligence .
// @router /intelligence/list [POST]
func GetIntelligence(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetIntelligenceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().IntelligenceService.GetIntelligenceInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
