// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/innospark-core-api/biz/adaptor"
	"github.com/xh-polaris/innospark-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/innospark-core-api/biz/application/dto/core_api"
)

// GenSignedURL .
// @router /system/get_signed_url [POST]
func GenSignedURL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GenSignedURLReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := provider.Get().AttachService.GenSignedURL(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
