// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: core_api/common.proto

package core_api

import (
	basic "github.com/xh-polaris/innospark-core-api/biz/application/dto/basic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单条消息
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content     string   `protobuf:"bytes,1,opt,name=content,proto3" form:"content" json:"content" query:"content"` // 消息内容, json字符串, 存放在text中
	ContentType int32    `protobuf:"varint,2,opt,name=contentType,proto3" form:"contentType" json:"contentType" query:"contentType"`
	Attaches    []string `protobuf:"bytes,3,rep,name=attaches,proto3" form:"attaches" json:"attaches" query:"attaches"`
	References  []string `protobuf:"bytes,4,rep,name=references,proto3" form:"references" json:"references" query:"references"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *Message) GetAttaches() []string {
	if x != nil {
		return x.Attaches
	}
	return nil
}

func (x *Message) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

// 对话配置
type CompletionOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRegen                bool `protobuf:"varint,1,opt,name=isRegen,proto3" form:"isRegen" json:"isRegen" query:"isRegen"`                                                             // 是否重新生成
	WithSuggest            bool `protobuf:"varint,2,opt,name=withSuggest,proto3" form:"withSuggest" json:"withSuggest" query:"withSuggest"`                                             // 是否生成建议
	NeedCreateConversation bool `protobuf:"varint,3,opt,name=needCreateConversation,proto3" form:"needCreateConversation" json:"needCreateConversation" query:"needCreateConversation"` // 是否需要创建新对话
	IsReplace              bool `protobuf:"varint,4,opt,name=isReplace,proto3" form:"isReplace" json:"isReplace" query:"isReplace"`                                                     // 是否替换
	IsDelete               bool `protobuf:"varint,5,opt,name=isDelete,proto3" form:"isDelete" json:"isDelete" query:"isDelete"`                                                         // 是否删除
	UseDeepThink           bool `protobuf:"varint,6,opt,name=useDeepThink,proto3" form:"useDeepThink" json:"useDeepThink" query:"useDeepThink"`                                         // 是否深度思考
}

func (x *CompletionOption) Reset() {
	*x = CompletionOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionOption) ProtoMessage() {}

func (x *CompletionOption) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionOption.ProtoReflect.Descriptor instead.
func (*CompletionOption) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionOption) GetIsRegen() bool {
	if x != nil {
		return x.IsRegen
	}
	return false
}

func (x *CompletionOption) GetWithSuggest() bool {
	if x != nil {
		return x.WithSuggest
	}
	return false
}

func (x *CompletionOption) GetNeedCreateConversation() bool {
	if x != nil {
		return x.NeedCreateConversation
	}
	return false
}

func (x *CompletionOption) GetIsReplace() bool {
	if x != nil {
		return x.IsReplace
	}
	return false
}

func (x *CompletionOption) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

func (x *CompletionOption) GetUseDeepThink() bool {
	if x != nil {
		return x.UseDeepThink
	}
	return false
}

// SSEEvent
type SSEEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventData string `protobuf:"bytes,1,opt,name=eventData,proto3" form:"eventData" json:"eventData" query:"eventData"`  // 事件数据
	EventId   int32  `protobuf:"varint,2,opt,name=eventId,proto3" form:"eventId" json:"eventId" query:"eventId"`         // 事件id
	EventType int32  `protobuf:"varint,3,opt,name=eventType,proto3" form:"eventType" json:"eventType" query:"eventType"` // 事件类型
}

func (x *SSEEvent) Reset() {
	*x = SSEEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSEEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSEEvent) ProtoMessage() {}

func (x *SSEEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSEEvent.ProtoReflect.Descriptor instead.
func (*SSEEvent) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *SSEEvent) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *SSEEvent) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SSEEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

// 消息元数据
type EventMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId        string `protobuf:"bytes,1,opt,name=messageId,proto3" form:"messageId" json:"messageId" query:"messageId"`                              // 消息id
	LocalMessageId   string `protobuf:"bytes,2,opt,name=localMessageId,proto3" form:"localMessageId" json:"localMessageId" query:"localMessageId"`          // 本地消息id
	ConversationId   string `protobuf:"bytes,3,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`          // 对话id
	SectionId        string `protobuf:"bytes,4,opt,name=sectionId,proto3" form:"sectionId" json:"sectionId" query:"sectionId"`                              // 段id
	MessageIndex     int32  `protobuf:"varint,5,opt,name=messageIndex,proto3" form:"messageIndex" json:"messageIndex" query:"messageIndex"`                 // 消息索引
	ConversationType int32  `protobuf:"varint,6,opt,name=conversationType,proto3" form:"conversationType" json:"conversationType" query:"conversationType"` // 对话类型
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{3}
}

func (x *EventMeta) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EventMeta) GetLocalMessageId() string {
	if x != nil {
		return x.LocalMessageId
	}
	return ""
}

func (x *EventMeta) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EventMeta) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *EventMeta) GetMessageIndex() int32 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *EventMeta) GetConversationType() int32 {
	if x != nil {
		return x.ConversationType
	}
	return 0
}

// 模型信息
type EventModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId   string `protobuf:"bytes,1,opt,name=botId,proto3" form:"botId" json:"botId" query:"botId"`         // 模型id
	BotName string `protobuf:"bytes,2,opt,name=botName,proto3" form:"botName" json:"botName" query:"botName"` // 模型名称
}

func (x *EventModel) Reset() {
	*x = EventModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventModel) ProtoMessage() {}

func (x *EventModel) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventModel.ProtoReflect.Descriptor instead.
func (*EventModel) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{4}
}

func (x *EventModel) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *EventModel) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

// 模型内容
type EventChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message          *EventChat_Message `protobuf:"bytes,1,opt,name=message,proto3" form:"message" json:"message" query:"message"`                                      // 消息内容
	MessageId        string             `protobuf:"bytes,2,opt,name=messageId,proto3" form:"messageId" json:"messageId" query:"messageId"`                              // 消息id
	LocalMessageId   string             `protobuf:"bytes,3,opt,name=localMessageId,proto3" form:"localMessageId" json:"localMessageId" query:"localMessageId"`          // 本地消息id
	ConversationId   string             `protobuf:"bytes,4,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`          // 对话id
	SectionId        string             `protobuf:"bytes,5,opt,name=sectionId,proto3" form:"sectionId" json:"sectionId" query:"sectionId"`                              // 段id
	ReplyId          string             `protobuf:"bytes,6,opt,name=replyId,proto3" form:"replyId" json:"replyId" query:"replyId"`                                      // 回复id
	IsDelta          bool               `protobuf:"varint,7,opt,name=isDelta,proto3" form:"isDelta" json:"isDelta" query:"isDelta"`                                     // 是否增量
	Status           int32              `protobuf:"varint,8,opt,name=status,proto3" form:"status" json:"status" query:"status"`                                         // 状态
	InputContentType int32              `protobuf:"varint,9,opt,name=inputContentType,proto3" form:"inputContentType" json:"inputContentType" query:"inputContentType"` // 输入内容类型
	MessageIndex     int32              `protobuf:"varint,10,opt,name=messageIndex,proto3" form:"messageIndex" json:"messageIndex" query:"messageIndex"`                // 消息索引
	BotId            string             `protobuf:"bytes,11,opt,name=botId,proto3" form:"botId" json:"botId" query:"botId"`                                             // 模型id
}

func (x *EventChat) Reset() {
	*x = EventChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChat) ProtoMessage() {}

func (x *EventChat) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChat.ProtoReflect.Descriptor instead.
func (*EventChat) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{5}
}

func (x *EventChat) GetMessage() *EventChat_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EventChat) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EventChat) GetLocalMessageId() string {
	if x != nil {
		return x.LocalMessageId
	}
	return ""
}

func (x *EventChat) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EventChat) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *EventChat) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *EventChat) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

func (x *EventChat) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EventChat) GetInputContentType() int32 {
	if x != nil {
		return x.InputContentType
	}
	return 0
}

func (x *EventChat) GetMessageIndex() int32 {
	if x != nil {
		return x.MessageIndex
	}
	return 0
}

func (x *EventChat) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

// 结束
type EventEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventEnd) Reset() {
	*x = EventEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnd) ProtoMessage() {}

func (x *EventEnd) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnd.ProtoReflect.Descriptor instead.
func (*EventEnd) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{6}
}

// 模型对话请求
type CompletionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages         []*Message        `protobuf:"bytes,1,rep,name=messages,proto3" form:"messages" json:"messages" query:"messages"`                                 // 用户输入消息, 长度应为1
	CompletionOption *CompletionOption `protobuf:"bytes,2,opt,name=completionOption,proto3" form:"completionOption" json:"completionOption" query:"completionOption"` // 对话配置
	BotId            string            `protobuf:"bytes,3,opt,name=botId,proto3" form:"botId" json:"botId" query:"botId"`                                             // 使用的模型id
	ConversationId   string            `protobuf:"bytes,4,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`         // 对话id
	LocalMessageId   string            `protobuf:"bytes,5,opt,name=localMessageId,proto3" form:"localMessageId" json:"localMessageId" query:"localMessageId"`         // 本地消息id
}

func (x *CompletionReq) Reset() {
	*x = CompletionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionReq) ProtoMessage() {}

func (x *CompletionReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionReq.ProtoReflect.Descriptor instead.
func (*CompletionReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{7}
}

func (x *CompletionReq) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionReq) GetCompletionOption() *CompletionOption {
	if x != nil {
		return x.CompletionOption
	}
	return nil
}

func (x *CompletionReq) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *CompletionReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CompletionReq) GetLocalMessageId() string {
	if x != nil {
		return x.LocalMessageId
	}
	return ""
}

// 获取历史记录请求
type ListHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page *basic.Page `protobuf:"bytes,1,opt,name=page,proto3" form:"page" json:"page" query:"page"`
}

func (x *ListHistoryReq) Reset() {
	*x = ListHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryReq) ProtoMessage() {}

func (x *ListHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryReq.ProtoReflect.Descriptor instead.
func (*ListHistoryReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{8}
}

func (x *ListHistoryReq) GetPage() *basic.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListHistoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *basic.Response            `protobuf:"bytes,1,opt,name=response,proto3" form:"response" json:"response" query:"response"`
	History  []*ListHistoryResp_HisItem `protobuf:"bytes,2,rep,name=history,proto3" form:"history" json:"history" query:"history"`
}

func (x *ListHistoryResp) Reset() {
	*x = ListHistoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryResp) ProtoMessage() {}

func (x *ListHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryResp.ProtoReflect.Descriptor instead.
func (*ListHistoryResp) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{9}
}

func (x *ListHistoryResp) GetResponse() *basic.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListHistoryResp) GetHistory() []*ListHistoryResp_HisItem {
	if x != nil {
		return x.History
	}
	return nil
}

// 获取历史记录
type GetHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page           *basic.Page `protobuf:"bytes,1,opt,name=page,proto3" form:"page" json:"page" query:"page"`
	ConversationId string      `protobuf:"bytes,2,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryReq) GetPage() *basic.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetHistoryReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetHistoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp        *basic.Response               `protobuf:"bytes,1,opt,name=resp,proto3" form:"resp" json:"resp" query:"resp"`
	MessageList []*GetHistoryResp_MessageList `protobuf:"bytes,2,rep,name=messageList,proto3" form:"messageList" json:"messageList" query:"messageList"`
	HasMore     bool                          `protobuf:"varint,3,opt,name=hasMore,proto3" form:"hasMore" json:"hasMore" query:"hasMore"`
}

func (x *GetHistoryResp) Reset() {
	*x = GetHistoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp) ProtoMessage() {}

func (x *GetHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp.ProtoReflect.Descriptor instead.
func (*GetHistoryResp) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryResp) GetResp() *basic.Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *GetHistoryResp) GetMessageList() []*GetHistoryResp_MessageList {
	if x != nil {
		return x.MessageList
	}
	return nil
}

func (x *GetHistoryResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// 获取智能体列表
type ListAgentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page *basic.Page `protobuf:"bytes,1,opt,name=page,proto3" form:"page" json:"page" query:"page"`
}

func (x *ListAgentsReq) Reset() {
	*x = ListAgentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsReq) ProtoMessage() {}

func (x *ListAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsReq.ProtoReflect.Descriptor instead.
func (*ListAgentsReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{12}
}

func (x *ListAgentsReq) GetPage() *basic.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAgentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp   *basic.Response         `protobuf:"bytes,1,opt,name=resp,proto3" form:"resp" json:"resp" query:"resp"`
	Agents []*ListAgentsResp_Agent `protobuf:"bytes,2,rep,name=agents,proto3" form:"agents" json:"agents" query:"agents"`
}

func (x *ListAgentsResp) Reset() {
	*x = ListAgentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResp) ProtoMessage() {}

func (x *ListAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResp.ProtoReflect.Descriptor instead.
func (*ListAgentsResp) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{13}
}

func (x *ListAgentsResp) GetResp() *basic.Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *ListAgentsResp) GetAgents() []*ListAgentsResp_Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// 反馈, 包括点赞, 点踩, 删除等
type FeedbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp      *basic.Response       `protobuf:"bytes,1,opt,name=resp,proto3" form:"resp" json:"resp" query:"resp"`
	Action    string                `protobuf:"bytes,2,opt,name=action,proto3" form:"action" json:"action" query:"action"`
	MessageId string                `protobuf:"bytes,3,opt,name=messageId,proto3" form:"messageId" json:"messageId" query:"messageId"`
	Feedback  *FeedbackReq_Feedback `protobuf:"bytes,4,opt,name=feedback,proto3" form:"feedback" json:"feedback" query:"feedback"`
}

func (x *FeedbackReq) Reset() {
	*x = FeedbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackReq) ProtoMessage() {}

func (x *FeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackReq.ProtoReflect.Descriptor instead.
func (*FeedbackReq) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{14}
}

func (x *FeedbackReq) GetResp() *basic.Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *FeedbackReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FeedbackReq) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *FeedbackReq) GetFeedback() *FeedbackReq_Feedback {
	if x != nil {
		return x.Feedback
	}
	return nil
}

type EventChat_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content     string `protobuf:"bytes,1,opt,name=content,proto3" form:"content" json:"content" query:"content"`
	ContentType int32  `protobuf:"varint,2,opt,name=contentType,proto3" form:"contentType" json:"contentType" query:"contentType"`
}

func (x *EventChat_Message) Reset() {
	*x = EventChat_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChat_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChat_Message) ProtoMessage() {}

func (x *EventChat_Message) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChat_Message.ProtoReflect.Descriptor instead.
func (*EventChat_Message) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{5, 0}
}

func (x *EventChat_Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EventChat_Message) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

type ListHistoryResp_HisItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
	Brief          string `protobuf:"bytes,2,opt,name=brief,proto3" form:"brief" json:"brief" query:"brief"`
	CreateTime     int64  `protobuf:"varint,3,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	UpdateTime     int64  `protobuf:"varint,4,opt,name=updateTime,proto3" form:"updateTime" json:"updateTime" query:"updateTime"`
}

func (x *ListHistoryResp_HisItem) Reset() {
	*x = ListHistoryResp_HisItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListHistoryResp_HisItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryResp_HisItem) ProtoMessage() {}

func (x *ListHistoryResp_HisItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryResp_HisItem.ProtoReflect.Descriptor instead.
func (*ListHistoryResp_HisItem) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ListHistoryResp_HisItem) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListHistoryResp_HisItem) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ListHistoryResp_HisItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ListHistoryResp_HisItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type GetHistoryResp_Ext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotState string `protobuf:"bytes,1,opt,name=bot_state,json=botState,proto3" form:"bot_state" json:"botState" query:"bot_state"` // json string, 对应EventModel
}

func (x *GetHistoryResp_Ext) Reset() {
	*x = GetHistoryResp_Ext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryResp_Ext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp_Ext) ProtoMessage() {}

func (x *GetHistoryResp_Ext) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp_Ext.ProtoReflect.Descriptor instead.
func (*GetHistoryResp_Ext) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetHistoryResp_Ext) GetBotState() string {
	if x != nil {
		return x.BotState
	}
	return ""
}

type GetHistoryResp_MessageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string              `protobuf:"bytes,1,opt,name=conversationId,proto3" form:"conversationId" json:"conversationId" query:"conversationId"`
	SectionId      string              `protobuf:"bytes,2,opt,name=sectionId,proto3" form:"sectionId" json:"sectionId" query:"sectionId"`
	MessageId      string              `protobuf:"bytes,3,opt,name=messageId,proto3" form:"messageId" json:"messageId" query:"messageId"`
	LocalMessageId string              `protobuf:"bytes,4,opt,name=localMessageId,proto3" form:"localMessageId" json:"localMessageId" query:"localMessageId"`
	Index          int32               `protobuf:"varint,5,opt,name=index,proto3" form:"index" json:"index" query:"index"`
	ReplyId        string              `protobuf:"bytes,6,opt,name=replyId,proto3" form:"replyId" json:"replyId" query:"replyId"` // 回复id
	Status         int32               `protobuf:"varint,7,opt,name=status,proto3" form:"status" json:"status" query:"status"`    // 状态, 目前默认0
	CreateTime     int64               `protobuf:"varint,8,opt,name=createTime,proto3" form:"createTime" json:"createTime" query:"createTime"`
	MessageType    int32               `protobuf:"varint,9,opt,name=messageType,proto3" form:"messageType" json:"messageType" query:"messageType"`
	ContentType    int32               `protobuf:"varint,10,opt,name=contentType,proto3" form:"contentType" json:"contentType" query:"contentType"`
	Content        string              `protobuf:"bytes,11,opt,name=content,proto3" form:"content" json:"content" query:"content"` // json string
	Ext            *GetHistoryResp_Ext `protobuf:"bytes,12,opt,name=ext,proto3" form:"ext" json:"ext" query:"ext"`
	Feedback       int32               `protobuf:"varint,13,opt,name=feedback,proto3" form:"feedback" json:"feedback" query:"feedback"` // 反馈类型
	UserType       int32               `protobuf:"varint,14,opt,name=userType,proto3" form:"userType" json:"userType" query:"userType"` // 用户类型, 如system, assistant, user
}

func (x *GetHistoryResp_MessageList) Reset() {
	*x = GetHistoryResp_MessageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHistoryResp_MessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResp_MessageList) ProtoMessage() {}

func (x *GetHistoryResp_MessageList) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResp_MessageList.ProtoReflect.Descriptor instead.
func (*GetHistoryResp_MessageList) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{11, 1}
}

func (x *GetHistoryResp_MessageList) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetLocalMessageId() string {
	if x != nil {
		return x.LocalMessageId
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetReplyId() string {
	if x != nil {
		return x.ReplyId
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetHistoryResp_MessageList) GetExt() *GetHistoryResp_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *GetHistoryResp_MessageList) GetFeedback() int32 {
	if x != nil {
		return x.Feedback
	}
	return 0
}

func (x *GetHistoryResp_MessageList) GetUserType() int32 {
	if x != nil {
		return x.UserType
	}
	return 0
}

type ListAgentsResp_Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BotId          string `protobuf:"bytes,1,opt,name=botId,proto3" form:"botId" json:"botId" query:"botId"`
	BotIcon        string `protobuf:"bytes,2,opt,name=botIcon,proto3" form:"botIcon" json:"botIcon" query:"botIcon"`
	BotName        string `protobuf:"bytes,3,opt,name=botName,proto3" form:"botName" json:"botName" query:"botName"`
	BotDescription string `protobuf:"bytes,4,opt,name=botDescription,proto3" form:"botDescription" json:"botDescription" query:"botDescription"`
}

func (x *ListAgentsResp_Agent) Reset() {
	*x = ListAgentsResp_Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsResp_Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResp_Agent) ProtoMessage() {}

func (x *ListAgentsResp_Agent) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResp_Agent.ProtoReflect.Descriptor instead.
func (*ListAgentsResp_Agent) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{13, 0}
}

func (x *ListAgentsResp_Agent) GetBotId() string {
	if x != nil {
		return x.BotId
	}
	return ""
}

func (x *ListAgentsResp_Agent) GetBotIcon() string {
	if x != nil {
		return x.BotIcon
	}
	return ""
}

func (x *ListAgentsResp_Agent) GetBotName() string {
	if x != nil {
		return x.BotName
	}
	return ""
}

func (x *ListAgentsResp_Agent) GetBotDescription() string {
	if x != nil {
		return x.BotDescription
	}
	return ""
}

type FeedbackReq_Feedback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" form:"type" json:"type" query:"type"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" form:"content" json:"content" query:"content"`
}

func (x *FeedbackReq_Feedback) Reset() {
	*x = FeedbackReq_Feedback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_api_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedbackReq_Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackReq_Feedback) ProtoMessage() {}

func (x *FeedbackReq_Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_core_api_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackReq_Feedback.ProtoReflect.Descriptor instead.
func (*FeedbackReq_Feedback) Descriptor() ([]byte, []int) {
	return file_core_api_common_proto_rawDescGZIP(), []int{14, 0}
}

func (x *FeedbackReq_Feedback) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *FeedbackReq_Feedback) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_core_api_common_proto protoreflect.FileDescriptor

var file_core_api_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0xe4, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73,
	0x52, 0x65, 0x67, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52,
	0x65, 0x67, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x53, 0x75, 0x67, 0x67,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x53,
	0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x6e, 0x65, 0x65, 0x64, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x44,
	0x65, 0x65, 0x70, 0x54, 0x68, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x75, 0x73, 0x65, 0x44, 0x65, 0x65, 0x70, 0x54, 0x68, 0x69, 0x6e, 0x6b, 0x22, 0x60, 0x0a, 0x08,
	0x53, 0x53, 0x45, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xe7,
	0x01, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2a, 0x0a, 0x10,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3c, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc7, 0x03, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x1a, 0x45, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x0a, 0x0a, 0x08, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x22, 0xec, 0x01, 0x0a,
	0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x2d,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x46, 0x0a,
	0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x85,
	0x02, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x48, 0x69, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x87, 0x01, 0x0a,
	0x07, 0x48, 0x69, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x85, 0x05, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x1a, 0x22, 0x0a, 0x03, 0x45, 0x78,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0xc7,
	0x03, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x2e, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x78, 0x74, 0x52, 0x03, 0x65, 0x78, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xe8, 0x01, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a,
	0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65,
	0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x79, 0x0a, 0x05, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x74,
	0x49, 0x63, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x74, 0x49,
	0x63, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xde, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x3a, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x1a, 0x38, 0x0a, 0x08,
	0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x68, 0x2d, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x69, 0x73, 0x2f,
	0x69, 0x6e, 0x6e, 0x6f, 0x73, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_api_common_proto_rawDescOnce sync.Once
	file_core_api_common_proto_rawDescData = file_core_api_common_proto_rawDesc
)

func file_core_api_common_proto_rawDescGZIP() []byte {
	file_core_api_common_proto_rawDescOnce.Do(func() {
		file_core_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_api_common_proto_rawDescData)
	})
	return file_core_api_common_proto_rawDescData
}

var file_core_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_core_api_common_proto_goTypes = []interface{}{
	(*Message)(nil),                    // 0: core_api.Message
	(*CompletionOption)(nil),           // 1: core_api.CompletionOption
	(*SSEEvent)(nil),                   // 2: core_api.SSEEvent
	(*EventMeta)(nil),                  // 3: core_api.EventMeta
	(*EventModel)(nil),                 // 4: core_api.EventModel
	(*EventChat)(nil),                  // 5: core_api.EventChat
	(*EventEnd)(nil),                   // 6: core_api.EventEnd
	(*CompletionReq)(nil),              // 7: core_api.CompletionReq
	(*ListHistoryReq)(nil),             // 8: core_api.ListHistoryReq
	(*ListHistoryResp)(nil),            // 9: core_api.ListHistoryResp
	(*GetHistoryReq)(nil),              // 10: core_api.GetHistoryReq
	(*GetHistoryResp)(nil),             // 11: core_api.GetHistoryResp
	(*ListAgentsReq)(nil),              // 12: core_api.ListAgentsReq
	(*ListAgentsResp)(nil),             // 13: core_api.ListAgentsResp
	(*FeedbackReq)(nil),                // 14: core_api.FeedbackReq
	(*EventChat_Message)(nil),          // 15: core_api.EventChat.Message
	(*ListHistoryResp_HisItem)(nil),    // 16: core_api.ListHistoryResp.HisItem
	(*GetHistoryResp_Ext)(nil),         // 17: core_api.GetHistoryResp.Ext
	(*GetHistoryResp_MessageList)(nil), // 18: core_api.GetHistoryResp.MessageList
	(*ListAgentsResp_Agent)(nil),       // 19: core_api.ListAgentsResp.Agent
	(*FeedbackReq_Feedback)(nil),       // 20: core_api.FeedbackReq.Feedback
	(*basic.Page)(nil),                 // 21: basic.Page
	(*basic.Response)(nil),             // 22: basic.Response
}
var file_core_api_common_proto_depIdxs = []int32{
	15, // 0: core_api.EventChat.message:type_name -> core_api.EventChat.Message
	0,  // 1: core_api.CompletionReq.messages:type_name -> core_api.Message
	1,  // 2: core_api.CompletionReq.completionOption:type_name -> core_api.CompletionOption
	21, // 3: core_api.ListHistoryReq.page:type_name -> basic.Page
	22, // 4: core_api.ListHistoryResp.response:type_name -> basic.Response
	16, // 5: core_api.ListHistoryResp.history:type_name -> core_api.ListHistoryResp.HisItem
	21, // 6: core_api.GetHistoryReq.page:type_name -> basic.Page
	22, // 7: core_api.GetHistoryResp.resp:type_name -> basic.Response
	18, // 8: core_api.GetHistoryResp.messageList:type_name -> core_api.GetHistoryResp.MessageList
	21, // 9: core_api.ListAgentsReq.page:type_name -> basic.Page
	22, // 10: core_api.ListAgentsResp.resp:type_name -> basic.Response
	19, // 11: core_api.ListAgentsResp.agents:type_name -> core_api.ListAgentsResp.Agent
	22, // 12: core_api.FeedbackReq.resp:type_name -> basic.Response
	20, // 13: core_api.FeedbackReq.feedback:type_name -> core_api.FeedbackReq.Feedback
	17, // 14: core_api.GetHistoryResp.MessageList.ext:type_name -> core_api.GetHistoryResp.Ext
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_core_api_common_proto_init() }
func file_core_api_common_proto_init() {
	if File_core_api_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_api_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSEEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompletionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventChat_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListHistoryResp_HisItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryResp_Ext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHistoryResp_MessageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentsResp_Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_api_common_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedbackReq_Feedback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_api_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_api_common_proto_goTypes,
		DependencyIndexes: file_core_api_common_proto_depIdxs,
		MessageInfos:      file_core_api_common_proto_msgTypes,
	}.Build()
	File_core_api_common_proto = out.File
	file_core_api_common_proto_rawDesc = nil
	file_core_api_common_proto_goTypes = nil
	file_core_api_common_proto_depIdxs = nil
}
