// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/innospark-core-api/biz/application/service"
	"github.com/xh-polaris/innospark-core-api/biz/domain/model"
	"github.com/xh-polaris/innospark-core-api/biz/infra/config"
	"github.com/xh-polaris/innospark-core-api/biz/infra/mapper/conversation"
	"github.com/xh-polaris/innospark-core-api/biz/infra/mapper/message"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := message.NewMessageMongoMapper(configConfig)
	messageDomain := &model.MessageDomain{
		MsgMapper: mongoMapper,
	}
	completionDomain := &model.CompletionDomain{
		MsgDomain: messageDomain,
	}
	completionsService := &service.CompletionsService{
		MsgMaMsgDomain:   messageDomain,
		CompletionDomain: completionDomain,
	}
	conversationMongoMapper := conversation.NewConversationMongoMapper(configConfig)
	conversationService := &service.ConversationService{
		ConversationMapper: conversationMongoMapper,
		MessageMapper:      mongoMapper,
	}
	providerProvider := &Provider{
		Config:              configConfig,
		CompletionsService:  completionsService,
		ConversationService: conversationService,
		MessageDomain:       messageDomain,
		CompletionDomain:    completionDomain,
	}
	return providerProvider, nil
}
