// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/innospark-core-api/biz/application/service"
	"github.com/xh-polaris/innospark-core-api/biz/infra/config"
	"github.com/xh-polaris/innospark-core-api/biz/infra/mapper/conversation"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	completionsService := &service.CompletionsService{}
	mongoMapper := conversation.NewConversationMongoMapper(configConfig)
	conversationService := &service.ConversationService{
		ConversationMapper: mongoMapper,
	}
	providerProvider := &Provider{
		Config:              configConfig,
		CompletionsService:  completionsService,
		ConversationService: conversationService,
	}
	return providerProvider, nil
}
