// Code generated by hertz generator. DO NOT EDIT.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	core_api "github.com/xh-polaris/innospark-core-api/biz/adaptor/controller/core_api"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	root.POST("/feedback", append(_feedback0Mw(), core_api.Feedback)...)
	_feedback := root.Group("/feedback", _feedbackMw()...)
	_feedback.POST("/content", append(_feedbackcontentMw(), core_api.FeedbackContent)...)
	{
		_admin := root.Group("/admin", _adminMw()...)
		_admin.POST("/forbidden", append(_forbiddenMw(), core_api.Forbidden)...)
		_admin.POST("/list_user", append(_listuserMw(), core_api.ListUser)...)
		_admin.POST("/login", append(_adminloginMw(), core_api.AdminLogin)...)
		{
			_feedback1 := _admin.Group("/feedback", _feedback1Mw()...)
			_feedback1.POST("/list", append(_listfeedbackMw(), core_api.ListFeedback)...)
		}
		{
			_statistic := _admin.Group("/statistic", _statisticMw()...)
			_statistic.POST("/user", append(_userstatisticMw(), core_api.UserStatistic)...)
		}
	}
	{
		_agents := root.Group("/agents", _agentsMw()...)
		_agents.POST("/list", append(_listagentsMw(), core_api.ListAgents)...)
	}
	{
		_basic_user := root.Group("/basic_user", _basic_userMw()...)
		_basic_user.POST("/login", append(_basicuserloginMw(), core_api.BasicUserLogin)...)
		_basic_user.GET("/profile", append(_basicusergetprofileMw(), core_api.BasicUserGetProfile)...)
		_basic_user.POST("/register", append(_basicuserregisterMw(), core_api.BasicUserRegister)...)
		_basic_user.POST("/reset_password", append(_basicuserresetpasswordMw(), core_api.BasicUserResetPassword)...)
		_basic_user.POST("/update_profile", append(_basicuserupdateprofileMw(), core_api.BasicUserUpdateProfile)...)
	}
	{
		_conversation := root.Group("/conversation", _conversationMw()...)
		_conversation.POST("/brief", append(_generateMw(), core_api.Generate)...)
		_conversation.POST("/create", append(_createconversationMw(), core_api.CreateConversation)...)
		_conversation.POST("/delete", append(_deleteconversationMw(), core_api.DeleteConversation)...)
		_conversation.POST("/get", append(_getconversationMw(), core_api.GetConversation)...)
		_conversation.POST("/list", append(_listconversationMw(), core_api.ListConversation)...)
		_conversation.POST("/rename", append(_renameconversationMw(), core_api.RenameConversation)...)
		_conversation.POST("/search", append(_searchconversationMw(), core_api.SearchConversation)...)
	}
	{
		_intelligence := root.Group("/intelligence", _intelligenceMw()...)
		_intelligence.POST("/get", append(_getintelligenceMw(), core_api.GetIntelligence)...)
		_intelligence.POST("/list", append(_listintelligenceMw(), core_api.ListIntelligence)...)
	}
	{
		_system := root.Group("/system", _systemMw()...)
		_system.POST("/check_verify_code", append(_checkverifycodeMw(), core_api.CheckVerifyCode)...)
		_system.POST("/gen_signed_url", append(_gensignedurlMw(), core_api.GenSignedURL)...)
		_system.POST("/send_verify_code", append(_sendverifycodeMw(), core_api.SendVerifyCode)...)
	}
	{
		_thirdparty := root.Group("/thirdparty", _thirdpartyMw()...)
		_thirdparty.POST("/login", append(_thirdpartyloginMw(), core_api.ThirdPartyLogin)...)
	}
	{
		_v1 := root.Group("/v1", _v1Mw()...)
		_v1.POST("/completions", append(_completionsMw(), core_api.Completions)...)
	}
}
