// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completionMw() []app.HandlerFunc {
	// your code...
	return nil
}
