// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _agentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listagentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _conversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _renameconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchconversationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basic_userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserresetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _intelligenceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listintelligenceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getintelligenceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartyloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserupdateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forbiddenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedback0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackcontentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedback1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}
